
# Nome do seu workflow
name: CI/CD 

on:
  push:
    branches: [ master ]

jobs:
  # JOB 1:iamgens
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build e Push do Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./backend 
          push: true
          tags: vininobre/backend:latest

      - name: Build e Push do Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./client 
          push: true
          tags: vininobre/frontend:latest


  deploy-to-k3s:
    runs-on: ubuntu-latest
    needs: build-and-push 

    steps:
      - name: Deploy k3s
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22

          # comandos na instancia K3s
          script: |
            echo "Conectado à instância K3s..."

            echo "reinicialização do Backend"
            sudo /usr/local/bin/k3s kubectl rollout restart deployment backend -n app-demo

            echo "reinicialização do Frontend"
            sudo /usr/local/bin/k3s kubectl rollout restart deployment frontend -n app-demo

            echo "Implantação concluída com sucesso!"